In [63]:
import numpy as np
#https://towardsdatascience.com/how-to-build-your-own-neural-network-from-scratch-in-python-68998a08e4f6

In [64]:
def sigmoid(t):
    return 1/(1+np.exp(-t))

In [65]:
def sigmoid_derivative(p):
    return p*(1-p)

In [111]:
class NeuralNetwork:
    def __init__(self, x, y):
        self.learning_rate = 5
        self.input = x
        self.weights1 = np.random.rand(self.input.shape[1], self.input.shape[1])#4)
        self.weights2 = np.random.rand(self.input.shape[1],1)#4,1)
        self.y = y
        self.output = np.zeros(self.y.shape)
    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = sigmoid(np.dot(self.layer1, self.weights2))
        return self.output
    def backpropagation(self):
        d_weights2 = np.dot(self.layer1.T, (2*(self.y-self.output)*sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T, (np.dot(2*(self.y-self.output)*sigmoid_derivative(self.output), self.weights2.T)*sigmoid_derivative(self.layer1)))
        self.weights1+=self.learning_rate*d_weights1
        self.weights2+=self.learning_rate*d_weights2
    def train(self, X, y):
        self.feedforward()
        self.backpropagation()
    def predict(self, X):
        self.input=X 
        return self.feedforward()

In [112]:
X = np.array(([0,0,1], [0,1,1], [1,0,1], [1,1,1]), dtype=float)
y = np.array(([0],[1],[1],[0]), dtype = float)

In [113]:
X.shape[1]

3

In [114]:
NN = NeuralNetwork(X,y)


In [115]:
for i in range(1000):
    if i%100 ==0:
        print ("for iteration # " + str(i) + "\n")
        print ("Input : \n" + str(X))
        print ("Actual Output: \n" + str(y))
        print ("Predicted Output: \n" + str(NN.feedforward()))
        print ("Loss: \n" + str(np.mean(np.square(y - NN.feedforward())))) # mean sum squared loss
        print ("\n")
  
    NN.train(X, y)

for iteration # 0

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.67084699]
 [0.72241678]
 [0.70155329]
 [0.74136272]]
Loss: 
0.29144431415861916


for iteration # 100

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.49889485]
 [0.50030792]
 [0.49883012]
 [0.500215  ]]
Loss: 
0.2499936360747862


for iteration # 200

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.39151016]
 [0.55231197]
 [0.48119397]
 [0.52994672]]
Loss: 
0.22592700108389646


for iteration # 300

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.02870707]
 [0.91983147]
 [0.97568165]
 [0.88636181]]
Loss: 
0.19836993088205868


for iteration # 400

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [

In [116]:
NN.predict(np.array([0,0,1]))

array([0.01060304])

In [117]:
X=np.array([1,1,1])
X.shape[0]
X

array([1, 1, 1])